version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:8080"
      - "443:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SA_PASSWORD=${DB_PASSWORD}
    networks:
      - mompos-network
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mompos-data:/var/opt/mssql
    networks:
      - mompos-network
    user: '0:0'

networks:
  mompos-network:

volumes:
  mompos-data: