version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:8080"
      - "443:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    networks:
      - mompos-network

  db:
    image: mcr.microsoft.com/mssql/server:2017-CU29-ubuntu
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mompos-data:/var/opt/mssql
    networks:
      - mompos-network

networks:
  mompos-network:

volumes:
  mompos-data: