// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MomPosApi.Data;

#nullable disable

namespace MomPosApi.Migrations
{
    [DbContext(typeof(MomPosContext))]
    [Migration("20240710182935_FixMenuItemOptionSchema")]
    partial class FixMenuItemOptionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MomPosApi.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MenuConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("MenuConfigurationId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MomPosApi.Models.MenuConfiguration", b =>
                {
                    b.Property<int>("MenuConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuConfigurationId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("MenuConfigurationId");

                    b.ToTable("MenuConfigurations");
                });

            modelBuilder.Entity("MomPosApi.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("MenuItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("MomPosApi.Models.MenuItemOption", b =>
                {
                    b.Property<int>("MenuItemOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemOptionId"));

                    b.Property<decimal>("AdditionalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int?>("MenuItemId1")
                        .HasColumnType("int");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("MenuItemOptionId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("MenuItemId1")
                        .IsUnique()
                        .HasFilter("[MenuItemId1] IS NOT NULL");

                    b.ToTable("MenuItemOptions");
                });

            modelBuilder.Entity("MomPosApi.Models.Category", b =>
                {
                    b.HasOne("MomPosApi.Models.MenuConfiguration", "MenuConfiguration")
                        .WithMany("Categories")
                        .HasForeignKey("MenuConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuConfiguration");
                });

            modelBuilder.Entity("MomPosApi.Models.MenuItem", b =>
                {
                    b.HasOne("MomPosApi.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MomPosApi.Models.MenuItemOption", b =>
                {
                    b.HasOne("MomPosApi.Models.MenuItem", "MenuItem")
                        .WithMany("MenuItemOptions")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomPosApi.Models.MenuItem", null)
                        .WithOne("MenuItemOption")
                        .HasForeignKey("MomPosApi.Models.MenuItemOption", "MenuItemId1");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("MomPosApi.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("MomPosApi.Models.MenuConfiguration", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("MomPosApi.Models.MenuItem", b =>
                {
                    b.Navigation("MenuItemOption");

                    b.Navigation("MenuItemOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
