name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull latest changes and replace secrets
        uses: appleboy/ssh-action@master
        timeout-minutes: 30
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/mom-pos-api
            echo "Pulling latest changes..."
            git pull origin main
            echo "DB_PASSWORD value (first 3 characters): ${DB_PASSWORD:0:3}..."
            echo "Building and starting containers..."
            docker compose build
            docker compose up -d
