name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        timeout-minutes: 30
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/mom-pos-api
            echo "Pulling latest changes..."
            git pull origin main
            echo "Replacing secrets in appsettings.Production.json..."
            sed -i "s/PLACEHOLDER_DB_PASSWORD/${DB_PASSWORD}/g" appsettings.Production.json
            echo "Displaying appsettings.Production.json for verification..."
            cat appsettings.Production.json
            echo "Building and starting containers..."
            docker compose build
            docker compose up -d
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}